language: cpp

env:
  - COVERALLS_REPO_TOKEN=Kxy8qUQosYS2QOzDqFjvVFVA2NQ4wefBj

compiler:
  - gcc

sudo: required
dist: trusty


before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install lcov
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55base

script:
  - source /opt/qt55/bin/qt55-env.sh
  - cd Teste
  - /opt/qt55/bin/qmake Testes.pro
  - make
  - ./Testes
  - rm *tst_*
  - rm main*

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
